on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  start-app-and-scan:
    name: Iniciar app e executar ZAP DAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          npm install

      - name: Iniciar aplicação em background
        run: |
          nohup npm start &

      - name: Instalar wait-on
        run: npm install -g wait-on

      - name: Aguardar aplicação estar disponível
        run: wait-on http://localhost:8000

      - name: Testar conexão com a aplicação
        run: curl -I http://localhost:8000

      - name: Executar ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8000'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Relatório de Vulnerabilidades DAST'
          fail_action: true
