name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install django gunicorn requests

      - name: Run application in background
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &

  zap-scan:
    runs-on: ubuntu-latest
    needs: build-and-run
    steps:
      - name: Wait for server to start
        run: sleep 15

      - name: Test server availability
        run: curl -I http://localhost:8000

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8000'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Relatório de Vulnerabilidades DAST da FinSecure'
          fail_action: true

